"""add explanation to quiz models

Revision ID: 669b2b2877ba
Revises: c5b0f113b9fb
Create Date: 2026-05-09 14:03:00.171009

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '669b2b2877ba'
down_revision = 'c5b0f113b9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_answers', sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quiz_questions', sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_questions', 'explanation')
    op.drop_column('quiz_answers', 'explanation')
    # ### end Alembic commands ###
