"""added database 2

Revision ID: 7fd129db4073
Revises: eb200753f1cf
Create Date: 2026-05-09 13:46:05.931198

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7fd129db4073'
down_revision = 'eb200753f1cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bosses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('boss_battles', sa.Column('boss_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'boss_battles', 'bosses', ['boss_id'], ['id'], ondelete='SET NULL')
    op.drop_column('student_model', 'madrosc')
    op.drop_column('student_model', 'doglebne_przygotowanie')
    op.drop_column('student_model', 'kompletnosc')
    op.drop_column('student_model', 'spojnosc')
    op.drop_column('student_model', 'poprawnosc_wyjasnien')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_model', sa.Column('poprawnosc_wyjasnien', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('student_model', sa.Column('spojnosc', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('student_model', sa.Column('kompletnosc', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('student_model', sa.Column('doglebne_przygotowanie', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('student_model', sa.Column('madrosc', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'boss_battles', type_='foreignkey')
    op.drop_column('boss_battles', 'boss_id')
    op.drop_table('bosses')
    # ### end Alembic commands ###
