"""add_boss_battle_stats

Revision ID: 8dc54eee839c
Revises: 25b929cf2b95
Create Date: 2026-05-09 16:03:16.365692

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8dc54eee839c'
down_revision = '25b929cf2b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boss_battles', sa.Column('boss_hp_start', sa.Integer(), nullable=False))
    op.add_column('boss_battles', sa.Column('boss_hp_end', sa.Integer(), nullable=False))
    op.add_column('boss_battles', sa.Column('player_damage_total', sa.Integer(), nullable=False))
    op.add_column('boss_battles', sa.Column('accuracy_avg', sa.Float(), nullable=False))
    op.add_column('boss_battles', sa.Column('combo_count', sa.Integer(), nullable=False))
    op.add_column('boss_battles', sa.Column('victory', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boss_battles', 'victory')
    op.drop_column('boss_battles', 'combo_count')
    op.drop_column('boss_battles', 'accuracy_avg')
    op.drop_column('boss_battles', 'player_damage_total')
    op.drop_column('boss_battles', 'boss_hp_end')
    op.drop_column('boss_battles', 'boss_hp_start')
    # ### end Alembic commands ###
