"""game level added

Revision ID: f30313d1e9c0
Revises: 8dc54eee839c
Create Date: 2026-05-10 13:28:31.669917

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f30313d1e9c0'
down_revision = '8dc54eee839c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('games', sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('training_questions', 'difficulty',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_questions', 'difficulty',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('games', 'icon')
    op.drop_column('games', 'difficulty')
    # ### end Alembic commands ###
