/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutLeaderboardRouteImport } from './routes/_layout/leaderboard'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutGamesNewRouteImport } from './routes/_layout/games/new'
import { Route as LayoutGamesGameIdTrainingRouteImport } from './routes/_layout/games/$gameId/training'
import { Route as LayoutGamesGameIdSummaryRouteImport } from './routes/_layout/games/$gameId/summary'
import { Route as LayoutGamesGameIdQuizRouteImport } from './routes/_layout/games/$gameId/quiz'
import { Route as LayoutGamesGameIdBossRouteImport } from './routes/_layout/games/$gameId/boss'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLeaderboardRoute = LayoutLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGamesNewRoute = LayoutGamesNewRouteImport.update({
  id: '/games/new',
  path: '/games/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGamesGameIdTrainingRoute =
  LayoutGamesGameIdTrainingRouteImport.update({
    id: '/games/$gameId/training',
    path: '/games/$gameId/training',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutGamesGameIdSummaryRoute =
  LayoutGamesGameIdSummaryRouteImport.update({
    id: '/games/$gameId/summary',
    path: '/games/$gameId/summary',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutGamesGameIdQuizRoute = LayoutGamesGameIdQuizRouteImport.update({
  id: '/games/$gameId/quiz',
  path: '/games/$gameId/quiz',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGamesGameIdBossRoute = LayoutGamesGameIdBossRouteImport.update({
  id: '/games/$gameId/boss',
  path: '/games/$gameId/boss',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/leaderboard': typeof LayoutLeaderboardRoute
  '/settings': typeof LayoutSettingsRoute
  '/games/new': typeof LayoutGamesNewRoute
  '/games/$gameId/boss': typeof LayoutGamesGameIdBossRoute
  '/games/$gameId/quiz': typeof LayoutGamesGameIdQuizRoute
  '/games/$gameId/summary': typeof LayoutGamesGameIdSummaryRoute
  '/games/$gameId/training': typeof LayoutGamesGameIdTrainingRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/leaderboard': typeof LayoutLeaderboardRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/games/new': typeof LayoutGamesNewRoute
  '/games/$gameId/boss': typeof LayoutGamesGameIdBossRoute
  '/games/$gameId/quiz': typeof LayoutGamesGameIdQuizRoute
  '/games/$gameId/summary': typeof LayoutGamesGameIdSummaryRoute
  '/games/$gameId/training': typeof LayoutGamesGameIdTrainingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/leaderboard': typeof LayoutLeaderboardRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/games/new': typeof LayoutGamesNewRoute
  '/_layout/games/$gameId/boss': typeof LayoutGamesGameIdBossRoute
  '/_layout/games/$gameId/quiz': typeof LayoutGamesGameIdQuizRoute
  '/_layout/games/$gameId/summary': typeof LayoutGamesGameIdSummaryRoute
  '/_layout/games/$gameId/training': typeof LayoutGamesGameIdTrainingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/leaderboard'
    | '/settings'
    | '/games/new'
    | '/games/$gameId/boss'
    | '/games/$gameId/quiz'
    | '/games/$gameId/summary'
    | '/games/$gameId/training'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/leaderboard'
    | '/settings'
    | '/'
    | '/games/new'
    | '/games/$gameId/boss'
    | '/games/$gameId/quiz'
    | '/games/$gameId/summary'
    | '/games/$gameId/training'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/leaderboard'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/games/new'
    | '/_layout/games/$gameId/boss'
    | '/_layout/games/$gameId/quiz'
    | '/_layout/games/$gameId/summary'
    | '/_layout/games/$gameId/training'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/leaderboard': {
      id: '/_layout/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LayoutLeaderboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/games/new': {
      id: '/_layout/games/new'
      path: '/games/new'
      fullPath: '/games/new'
      preLoaderRoute: typeof LayoutGamesNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/games/$gameId/training': {
      id: '/_layout/games/$gameId/training'
      path: '/games/$gameId/training'
      fullPath: '/games/$gameId/training'
      preLoaderRoute: typeof LayoutGamesGameIdTrainingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/games/$gameId/summary': {
      id: '/_layout/games/$gameId/summary'
      path: '/games/$gameId/summary'
      fullPath: '/games/$gameId/summary'
      preLoaderRoute: typeof LayoutGamesGameIdSummaryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/games/$gameId/quiz': {
      id: '/_layout/games/$gameId/quiz'
      path: '/games/$gameId/quiz'
      fullPath: '/games/$gameId/quiz'
      preLoaderRoute: typeof LayoutGamesGameIdQuizRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/games/$gameId/boss': {
      id: '/_layout/games/$gameId/boss'
      path: '/games/$gameId/boss'
      fullPath: '/games/$gameId/boss'
      preLoaderRoute: typeof LayoutGamesGameIdBossRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutLeaderboardRoute: typeof LayoutLeaderboardRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutGamesNewRoute: typeof LayoutGamesNewRoute
  LayoutGamesGameIdBossRoute: typeof LayoutGamesGameIdBossRoute
  LayoutGamesGameIdQuizRoute: typeof LayoutGamesGameIdQuizRoute
  LayoutGamesGameIdSummaryRoute: typeof LayoutGamesGameIdSummaryRoute
  LayoutGamesGameIdTrainingRoute: typeof LayoutGamesGameIdTrainingRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutLeaderboardRoute: LayoutLeaderboardRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutGamesNewRoute: LayoutGamesNewRoute,
  LayoutGamesGameIdBossRoute: LayoutGamesGameIdBossRoute,
  LayoutGamesGameIdQuizRoute: LayoutGamesGameIdQuizRoute,
  LayoutGamesGameIdSummaryRoute: LayoutGamesGameIdSummaryRoute,
  LayoutGamesGameIdTrainingRoute: LayoutGamesGameIdTrainingRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
